# Generated by Django 5.0.4 on 2024-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_title_expense_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='share',
            name='share_currency',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='share',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
