# Generated by Django 5.0.4 on 2024-04-14 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_user_share_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
