# Generated by Django 5.0.4 on 2024-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
    ]
