# Generated by Django 5.0.4 on 2024-04-18 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='expenses_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='settler',
            field=models.ForeignKey(blank=True, help_text='Who has to pay for this share', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='share',
            field=models.DecimalField(decimal_places=2, help_text='share amount', max_digits=10),
        ),
    ]
