# Generated by Django 5.0.4 on 2024-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_participants_alter_share_payer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='comment',
            field=models.TextField(blank=True, help_text='Add a comment[OPTIONAL].', null=True),
        ),
    ]
